name: unwired
description: Unwired is a client library for handling (authenticated) multi-threaded disposable network calls, data parsing and authentication in applications.
version: 0.8.0
homepage: https://github.com/Ayush-Suman/unwired

environment:
  sdk: ">=2.17.0 <3.7.12"

dependencies:
  http: ^0.13.5


dev_dependencies:
  lints: ^2.0.1
  test: ^1.16.9
