name: unwired
description: Unwired is a fast and minimalistic Dart HTTP client library. It supports cancellable requests, managed authentication and multithreaded requests.
version: 0.8.3
homepage: https://github.com/Ayush-Suman/unwired

environment:
  sdk: ">=2.17.0 <3.7.12"

dependencies:
  http: ^0.13.5
  store_manager: ^1.0.1
  queue_manager: ^1.0.0
  http_worker: ^1.0.0
  auth_manager: ^1.0.0


dev_dependencies:
  lints: ^2.0.1
  test: ^1.16.9
