name: unwired
description: Unwired is a fast and minimalistic Dart HTTP client library. It supports cancellable requests, managed authentication and multithreaded requests.
version: 0.9.7
homepage: https://github.com/Ayush-Suman/unwired

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http_worker: ^1.3.5
  auth_manager: ^1.2.1
  store_manager: ^1.1.0
  queue_manager: ^1.1.0
  http_parser: ^4.0.2



dev_dependencies:
  lints: ^2.0.1
  test: ^1.16.9
