name: unwired
description: Unwired is a client library for handling (authenticated) multi-threaded disposable network calls, data parsing and authentication in applications.
version: 0.7.1
homepage: https://github.com/Ayush-Suman/unwired

environment:
  sdk: ">=2.17.0 <3.7.12"

dependencies:
  http: ^0.13.5
  flutter_secure_storage: ^8.0.0


dev_dependencies:
  test: ^1.16.9